### ISSUE TITLE
[Test] Conversion playlists locales > iris:playlists avec file:

### ISSUE THREAD

**Issue by pvincent4** [akago-dev/o2m#37]

**Comment by pvincent4** [comment]
https://www.makeuseof.com/tag/ways-to-import-playlists-into-spotify/

**Comment by akago-dev** [comment]
https://spotipy.readthedocs.io/en/2.12.0/?highlight=create%20playlist#spotipy.client.Spotify.user_playlist_create <https://spotipy.readthedocs.io/en/2.12.0/?highlight=create%20playlist#spotipy.client.Spotify.user_playlist_create> 

Avec l’outil déjà en place spotifyHandler dans notre code je crois, on peut créer une playlist sur le compte Spotify connecté.

Puis ajouter des titres dans la playlist créée : 

https://spotipy.readthedocs.io/en/2.12.0/?highlight=create%20playlist#spotipy.client.Spotify.user_playlist_add_tracks <https://spotipy.readthedocs.io/en/2.12.0/?highlight=create%20playlist#spotipy.client.Spotify.user_playlist_add_tracks>

Il faut par contre retrouver les ids Spotify de chaque titre avant, ce qui va faire surement faire un algorithme assez long à exécuter. Je pense qu’il faudra passer par la partie search de Spotipy

https://spotipy.readthedocs.io/en/2.12.0/?highlight=search#spotipy.client.Spotify.search <https://spotipy.readthedocs.io/en/2.12.0/?highlight=search#spotipy.client.Spotify.search>
 
Par contre, aucun moyen de créer des dossiers de playlist pour l’utilisateurs (ni de placer une playlist dans un dossier existant). Ca aurait été pratique pour ranger les playlist générées dans un dossier spécifique et pas alourdir l’interface Spotify.



Antoine Josnin
+33 (0)6 83 59 26 31
www.akago.fr <http://www.akago.fr/>

**Comment by pvincent4** [comment]
Merci ;) Ca sera peut être l'ultime option de refaire une moulinette ad-hoc.
Ma reflexion actuelle est de savoir comment mettre au meilleur endroit ses playlists pour ne pas les perdre sur le long terme et qu'elles puissent être utilisées dans toutes leurs capacités (en mobilité et être enrichies par exemple). 
Une solution pour commencer est surement d'encapsuler des playlist spotify dans une playslists iris.

Pour les conversions, j'ai testé https://www.tunemymusic.com/fr/ ça marche plutot bien
